services:
  coindrafts:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/build
      - /build/frontend/node_modules
    ports:
      - "5173:5173" # Frontend
      - "8080:8080" # Linera faucet
      - "8081:8081" # GraphQL service
      - "9001:9001" # Localnet validator proxy
      - "13001:13001" # Localnet validator
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
